model_large:
  name: "ZhipuAI/GLM-4.5"
  key: "ms-b052e4ed-4183-4027-8574-9b8f6fc9ad56"
  url: "https://api-inference.modelscope.cn/v1"

model_small:
  name: "XGenerationLab/XiYanSQL-QwenCoder-32B-2504"
  key: "ms-b052e4ed-4183-4027-8574-9b8f6fc9ad56"
  url: "https://api-inference.modelscope.cn/v1"

database:
  host: "10.0.13.10"
  port: 9030
  user: "root"
  password: "Cetc@123"
  database: "sjfx_dws"