model_large:
  name: "ZhipuAI/GLM-4.5"
  key: ""
  url: "https://api-inference.modelscope.cn/v1"

model_small:
  name: "XGenerationLab/XiYanSQL-QwenCoder-32B-2504"
  key: ""
  url: "https://api-inference.modelscope.cn/v1"

database:
  host: ""
  port: 
  user: ""
  password: ""
  database: ""
